services:
  db:
    image: postgres:16
    container_name: better_auth_postgres
    restart: always
    ports:
      - '8080:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: better_auth_pgadmin
    restart: always
    ports:
      - '8081:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: user@example.com
      PGADMIN_DEFAULT_PASSWORD: user
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data:
